### ISSUE TITLE
Look for .wundertools as root path, instead of looking for wundertools.settings.yml

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertool-py#1]
Can we migrate to using a .wundertools folder in the project root, that contains that wundertools settings yml file?

````
  {project}
  \ .wundertools                  --> root for all wundertools elements
      \ wundertools.settings.yml   --> wundertools settings
````

Advantages:

- we can put other things into the file, allowing us to further diversify settings

Disadvantages:

- perhaps using a dotfile makes it a little uglier (maybe a different file name)

**Comment by aleksijohansson** [comment]
@james-nesbitt Do you have any practical use case for this already or is it just future proofing?

**Comment by james-nesbitt** [comment]
future proofing.  I can imagine that a single yml file will never be enough to handle all tool settings, and makes it difficult to modularly build a template.

**Comment by aleksijohansson** [comment]
Implemented the feature with a folder called `wundertool` and the main settings file called `settings.yml` in the folder.
